### ISSUE TITLE
Package doesn't work anymore?

### ISSUE THREAD

**Issue by AntiChrist-Coder** [aprilahijriyan/selenium-fetch#1]
Response: None
Exception ignored in: <function Chrome.__del__ at 0x000001758B303920>
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid

**Comment by aprilahijriyan** [comment]
@AntiChrist-Coder Hello, sorry for the slow response.

This seems to be an issue with the `undetected-chromedriver` module.

See the following issue: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/955
